name: Hands on Git Docker Image
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'git-workshop/**'


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2


      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io
          username: scottmuc


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./git-workshop
          platforms: linux/amd64,linux/arm64
          push: true
          tags: scottmuc/handsongit:latest
